baseURL = 'https://passatelly.github.io/'
title = "Passatelly's blog"
theme = "etch"
languageCode = 'it-IT'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Sagace gioco di parole"
  copyright = "Copyright © 2022 Passatelly"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
